function test_docs()
    @testset "-> Website docs" begin
        docs_home = read(joinpath(QUBOLib.root_path(), "docs", "src", "index.md"), String)
        intro = read(joinpath(QUBOLib.root_path(), "docs", "src", "manual", "0-intro.md"), String)
        basic = read(joinpath(QUBOLib.root_path(), "docs", "src", "manual", "1-basic.md"), String)
        advanced = read(joinpath(QUBOLib.root_path(), "docs", "src", "manual", "2-advanced.md"), String)
        qoblib = read(joinpath(QUBOLib.root_path(), "docs", "src", "manual", "3-qoblib.md"), String)

        @test occursin("Retrieving instances", docs_home)
        @test occursin("Julia artifact", docs_home)
        @test occursin("QUBOLib.access", docs_home)
        @test occursin("QUBOLib.load_instance", docs_home)
        @test occursin("delete the local `qubolib`", docs_home)
        @test occursin("Pkg.add([\"SQLite\", \"DataFrames\"])", docs_home)
        @test occursin("donate challenging QUBOs", docs_home)

        math_heading = findfirst("## Mathematical Definitions", intro)
        benchmark_heading =
            findfirst("## Benchmarking Physics-Inspired Optimization Solvers", intro)

        @test !isnothing(math_heading)
        @test !isnothing(benchmark_heading)
        @test first(math_heading) < first(benchmark_heading)
        @test occursin("Benchmarking Physics-Inspired Optimization Solvers", intro)
        @test occursin("Instances", intro)
        @test occursin("Submissions", intro)
        @test occursin("SolutionRecords", intro)
        @test occursin("BestSolutions", intro)
        @test occursin("QUBOLib.load_instance", intro)
        @test occursin("QUBOTools.value", intro)
        @test occursin("QUBOLib.load_best_solution", intro)
        @test occursin("QUBOLib.best_solution_record", intro)
        @test occursin("QUBOLib.list_solution_records", intro)
        @test occursin("canonical benchmark comparator is `qubo_value`", intro)
        @test occursin("`source_value` is provenance", intro)
        @test occursin("solver stacks such as QUBODrivers", intro)
        @test occursin("```@example benchmarking-workflow", intro)
        @test occursin("zero-fill", intro)
        @test occursin("one-fill", intro)
        @test occursin("real packaged QOBLIB query", intro)
        @test occursin("i.collection = 'qoblib'", intro)
        @test occursin("source_value_agrees", intro)

        @test occursin("Opening the library index", basic)
        @test occursin("Loading an instance", basic)
        @test occursin("QUBOLib.database", basic)
        @test occursin("QUBOLib.load_instance", basic)
        @test occursin("Pkg.add([\"SQLite\", \"DataFrames\"])", basic)

        @test occursin("Adding a new collection", advanced)
        @test occursin("QUBOLib.add_collection!", advanced)
        @test occursin("QUBOLib.add_instance!", advanced)
        @test occursin("Pkg.add(\"QUBOTools\")", advanced)
        @test occursin("`clear = true` deletes any existing local QUBOLib data", advanced)
        @test occursin("Collection metadata", advanced)
        @test occursin("Packaged artifact workflow", advanced)
        @test occursin("donate", advanced)

        @test occursin("Constrained Class Inventory", qoblib)
        @test occursin("80e45c176fc6281e5316451f02296482934785fa", qoblib)
        @test occursin("a686aaa09fe14651294f744f34d453d5dce9cf57", qoblib)
        @test occursin("GitHub releases at that time", qoblib)
        @test occursin("zero blobs ending in `.qs` or `.qs.xz`", qoblib)
        @test occursin("metric metadata, not as retrievable QS artifacts", qoblib)
        @test occursin("Birkhoff Polytope", qoblib)
        @test occursin("Steiner Tree", qoblib)
        @test occursin("Sports Timetabling", qoblib)
        @test occursin("Network Design", qoblib)
        @test occursin("Capacitated Vehicle Routing", qoblib)
        @test occursin("Graph Topology Design", qoblib)
        @test occursin("No `.qs` or `.qs.xz` files", qoblib)
        @test occursin("Unavailable for canonical ingestion", qoblib)
        @test occursin("explicit naming and provenance", qoblib)
    end

    return nothing
end
