[collections]
git-tree-sha1 = "d7d51aa6610e8368cb794bb5e3f94529b243ffb8"
lazy          = true

    [[collections.download]]
    url    = "https://github.com/pedromxavier/QUBOInstancesData.jl/releases/download/v0.0.7/collections.tar.gz"
    sha256 = "897969fb0bd42bf1dc762dc610c0a4737f93db9e8e06d8ad329802f21a1c647a"