[collections]
git-tree-sha1 = "686ba6cb4d9ba576d79cafa3a5999bfcc34faab2"
lazy          = true

    [[collections.download]]
    url    = "https://github.com/pedromxavier/QUBOInstancesData.jl/releases/download/v0.0.10/collections.tar.gz"
    sha256 = "5c9e3e1dbb55123a4559ef90273a71ff76928a0a6ea15ad5ae9fcdb8ea23cea8"