[qubolib]
git-tree-sha1 = "589afc4ab896a18e91989bfb46448e6859c7d041"
lazy          = true

    [[qubolib.download]]
    url    = "https://github.com/JuliaQUBO/QUBOLib.jl/releases/download/v0.1.0-dev0/qubolib.tar.gz"
    sha256 = "fe76c53cf89075aa88c16ddde174f312f9917a10bf6a1900cbd2cdf3198c5d6f"
    