[qubolib]
git-tree-sha1 = "ec1bcbf0421a4fa1bc799285923496b5ebea6886"
lazy          = true

    [[qubolib.download]]
    url    = "https://github.com/pedromxavier/QUBOLibData.jl/releases/download/v0.1.1/qubolib.tar.gz"
    sha256 = "e6aa694a6ad0f49cc391fdf7146d3923f9e955518fbc397030f28d79a17c3605"