[collections]
git-tree-sha1 = "23712d4ae269a0c62c949159bbcd7f075f83db9a"
lazy          = true

    [[collections.download]]
    url    = "https://github.com/pedromxavier/QUBOInstancesData.jl/releases/download/v0.0.6/collections.tar.gz"
    sha256 = "df789b9d7f474cc213540861656fd4eb58ee8eceb2d327caa74611e74a1c7690"