[qubolib]
git-tree-sha1 = "7dd4e0ff8e24c29964698c5bcdcb167a5bf5f11d"
lazy          = true

    [[qubolib.download]]
    url    = "https://github.com/pedromxavier/QUBOLibData.jl/releases/download/v0.1.3/qubolib.tar.gz"
    sha256 = "e4acf4fb9c07b139b4eda3a46429bf685a097051a73b489b2c2b063f6c0979ce"
    