[qubolib]
git-tree-sha1 = "90da567266bc93ffb76cc0435691409557d500fc"
lazy          = true

    [[qubolib.download]]
    url    = "https://github.com/JuliaQUBO/QUBOLib.jl/releases/download/v0.2.4-data+4/qubolib.tar.gz"
    sha256 = "276eb06a66cec325cd3ec895cded7ba28f848aeb3998f4944466acbb33bcd001"
