[collections]
git-tree-sha1 = "06c91f9f2fd34d59b4c54987a77bd2c06fcb03d5"
lazy          = true

    [[collections.download]]
    url    = "https://github.com/pedromxavier/QUBOInstancesData.jl/releases/download/v0.0.8/collections.tar.gz"
    sha256 = "4b615a1d2dafcbfbb15d12abd60ecacb8a24cc42413b6cb0cb8aaa22365aa04e"