name = "QUBOInstances"
uuid = "c2d3eca2-2309-4628-88a9-9d4a554e7c47"
authors = ["Pedro Maciel Xavier <pedromxavier@poli.ufrj.br>"]
version = "0.1.0"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"
