name: Documentation
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - name: Develop QUBOLib.jl
        run: julia --project=docs -e 'using Pkg; Pkg.develop(path=pwd())'
      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1
        with: 
            project: "docs"
      - name: Build documentation
        run: julia --project=docs docs/make.jl --skip-deploy

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - name: Develop QUBOLib.jl
        run: julia --project=docs -e 'using Pkg; Pkg.develop(path=pwd())'
      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1
        with:
            project: "docs"
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs docs/make.jl
