name: Documentation
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Develop QUBOLib.jl
        run: julia --project=docs -e 'using Pkg; Pkg.develop(path=pwd())'
      - name: Build Package
        uses: julia-actions/julia-buildpkg@latest
        with: 
            project: "docs"
      - name: Build documentation
        if: github.event_name == 'pull_request'
        run: julia --project=docs docs/make.jl --skip-deploy
      - name: Build and deploy
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs docs/make.jl
